# Generated by Django 5.1.2 on 2024-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('procedimento', models.CharField(max_length=200)),
                ('data_procedimento', models.DateTimeField()),
                ('valor_procedimento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nome_dentista', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
